### ISSUE TITLE
Enable Bitcode in your framework

### ISSUE THREAD

**Issue by daxinipratik710** [Darktt/CollectionViewCell-Mover-Demo#1]
Hello Darktt,

I have checked this library and frameworks. its awesome but, I am finding one issue in your framework is bitcode error. so Please update your framework using bitcode. When you archive your project, its getting error.

**Comment by Darktt** [comment]
Thank you, 

I'll find out what the problem cannot enable bitcode.

**Comment by Darktt** [comment]
That framework only for my personal use, in this project, did not used any function in that framework,
I'm sorry.
